name: Distribute executables

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - run: pip install pyinstaller
    - run: scripts/build.sh
    - run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/github-script@v6
      with:
        script: |
          const { repo: { owner, repo }} = context;
          const release = await github.rest.repos.createRelease({ owner, repo, tag_name: "${{ env.GIT_TAG }}" });
          for (const name of ["protonvpn-darwin-arm64.tar.gz", "protonvpn-checksums.txt"]) {
            const data = `dist/${name}`;
            const { data: { id: release_id, upload_url: origin }} = release;
            await github.rest.repos.uploadReleaseAsset({ owner, repo, release_id, name, data, origin });
          }
